# Generated by Django 2.1.4 on 2018-12-05 13:50

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181205_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
